version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: cybercrime_db
    environment:
      POSTGRES_DB: cybercrime_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cybercrime_network

volumes:
  postgres_data:

networks:
  cybercrime_network:
    driver: bridge