version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: cybercrime_db
    environment:
      POSTGRES_DB: cybercrime_db
      POSTGRES_USER: cybercrime_user
      POSTGRES_PASSWORD: anabil
    ports:
      - "5433:5432"  # Changed to use port 5433 on host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cybercrime_network

volumes:
  postgres_data:

networks:
  cybercrime_network:
    driver: bridge